spring:
  data:
    mongodb:
      uri: mongodb://host.minikube.internal:27017/test
  datasource:
    url: jdbc:mysql://host.minikube.internal:3306/test
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: host.minikube.internal
    port: 6379

service:
  resource: service.json

