apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svcm
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: m-http
    path: /metrics
  namespaceSelector:
    any: true